### ISSUE TITLE
Dark theme circle friend icons have a white circle around them.

### ISSUE THREAD

**Issue by mewe123** [outsetini/Air-for-Steam#102]
As the title says the friends list in the dark theme have a white circle around them, as seen here http://i.imgur.com/6ifu6Si.png http://i.imgur.com/yJX47WJ.png A similar thing happens when a friend comes online or you get any popup message, except there is a gray-ish square around the icon. Honestly if this whole thing was a smaller and had that gray tint this would be alright.

**Comment by outsetini** [comment]
Make sure you've copied the contents of the +Extras dark theme folder into your Air directory: https://github.com/outsetini/Air-for-Steam/wiki#themes

If the issue still exists, feel free to re-open this issue. Cheers!
