### ISSUE TITLE
Speaker setup in advanced client options for in-home streaming displayed incorrectly

### ISSUE THREAD

**Issue by Chais** [outsetini/Air-for-Steam#105]
Settings > In-Home Streaming > Advanced Client Options
The speaker setup option is not displayed properly. It should go below the other two drop-down menus.
![bildschirmfoto von 2016-03-09 18-18-21](https://cloud.githubusercontent.com/assets/1783098/13643901/630b1324-e623-11e5-9c43-d2eec8a28837.png)

**Comment by DirtDiglett** [comment]
Use the official release of 1.0.1, as this should already be fixed. I don't support any third party modifications as they'll typically be out of date

**Comment by Chais** [comment]
This is with the Release: 2016-0117

**Comment by outsetini** [comment]
Thanks for the report, much appreciated. :+1:
