### ISSUE TITLE
Taskbar preferences overlap

### ISSUE THREAD

**Issue by KovuTheHusky** [outsetini/Air-for-Steam#106]
Running 2016-0311.

Settings > Interface > Set Taskbar Preferences has overlapping items, namely the new "SteamVR" item, as of March 11 Steam Beta Client update.

![taskbarprefs](https://cloud.githubusercontent.com/assets/361739/13722280/2f7da2f0-e80e-11e5-8eca-44a4426d5b1f.png)

**Comment by charlesmilette** [comment]
Also happens with Air Classic

**Comment by outsetini** [comment]
This is fixed on the develop branch for now, I will roll it out when the beta goes live. Feel free to download from develop in the meantime, thanks guys!
