### ISSUE TITLE
Empty notifications

### ISSUE THREAD

**Issue by Lartza** [Outsetini/Air-for-Steam#111]
I've actually had this issue on 0311 too, now I updated to 0403 and it persists.

Sometimes notifications, chat, achievement or game invitation, just show you the user avatar and name while the notification body is empty.

I think this happens with long messages, haven't seen this happen with just short messages and "has started playing" seems to work.

**Comment by Lartza** [comment]
I just asked my friend to send a few messages, äö didn't cause the problem, a long message did.

And I am on Linux by the way, attached is an image of the problem.

![kuvakaappaus 2016-04-14 10-56-45](https://cloud.githubusercontent.com/assets/305616/14520994/eeffe7b0-022f-11e6-84f9-1ddbafcb8d8e.png)

**Comment by Outsetini** [comment]
Hrm, that is extremely odd. I'm actually stumped as to what might be causing the issue. The code for the chat notifications is the same as the now playing notifications for all intensive purposes...

Can you check the default skin on Linux to see if it has similar issues?

**Comment by Lartza** [comment]
I'd never noticed anything before switching to Air, asked my friend to send a copy paste of our whole chat history again and it shows start of the message fine.

And yeah if I am not completely mistaken, now playing notifications seemed to always work and cut long game names while chat notifications are empty for long messages.

Achievement notifications have been empty too but that is harder to debug(I think I've only seen it once so far on Air once working and once not working). I would assume long achievement name causes that too.

I'll keep monitoring with default skin for now and report back but so far it seemed fine with the one test.

**Comment by Outsetini** [comment]
No joke about the achievement notifications... that might be one of the worst possible things to try to test. I played through the entire story mode of FEZ before managing to get the notification to a passable state.

I'll be honest, if this is a Linux only bug, I might not be able to assist much since I only have easy access to Windows. I'm happy to try to help if we are able to narrow it down to something actionable. Have you tried out any of the other skins, maybe Pressure or Metro? Might help to know if it's all skins or just Air.

**Comment by Lartza** [comment]
I tried Pressure, and the chat notifications work :/ I realized I did not disclose that I am on the Beta client, but I think I am on Windows too and do not have this problem. I haven't had much time to look into this but when I do I'll actually dig into the skin files a bit maybe.

**Comment by Outsetini** [comment]
Gotcha, well, let me know if you discover anything. If you do end up digging around a bit, the notification files are mostly in this folder: \Steam\skins\Air-for-Steam\Friends

**Comment by Lartza** [comment]
Well that was more easy than it could have ever been, I have found the culprit :)

I first fixed some errors in my system, I was missing lib32 murrine and adwaita but that did not help, so then I got actually in to Air.

I wanted to compare why Pressure would work and Air not, and I found this commit.
https://github.com/DirtDiglett/Pressure-for-Steam/commit/fb2e3bed0ce5d2be4d489b36694c2ba2f26928aa

Sounds easy enough, and adding font-size=15 [$LINUX] in ChatMsgNotification.res shows chat messages correctly, great!
![kuvakaappaus 2016-04-25 10-29-05](https://cloud.githubusercontent.com/assets/305616/14776685/b6cf7b90-0ad0-11e6-9eff-f832a43c6f7f.png)
(I accidentally screenshot a bit of my second monitor too that's why it's weird)

Previously he seemed to change margins on Linux back in 2014 , but this seems to be the latest fix. Not sure why Linux font-size has been reduced all over (remain style and consistency maybe) but I haven't had problems elsewhere than notifications.

**Comment by Outsetini** [comment]
Did you add that font size declaration into the Label style? If so, I can go ahead and try to apply that globally to notifications and see if that helps overall. LMK!

**Comment by Lartza** [comment]
Yes
`Label { font-family=medium font-size=16 font-size=15 [$LINUX] font-weight=500 textcolor=A2TextNotification font-style=regular }`

Worked for Friends/ChatMsgNotification.res

Pressure had a default font of 15 and reduced that to 14 so that's what I did here, 1px font size reduction, both probably work so it's all up to looks.

**Comment by Outsetini** [comment]
Can you give the latest commit a try and see if that fixes your issue? I added the font size declaration to all the notification files.

Please re-open if the issue persists, but I've got my fingers crossed!

**Comment by Lartza** [comment]
Putting it to the test starting now. Thanks for the great skin :)

**Comment by zanderzhng** [comment]
This also fixed the text bug of CJK chars in chat window, thank you.

**Comment by Outsetini** [comment]
Well, that's good news. :D
