### ISSUE TITLE
Text glitch on OS X.

### ISSUE THREAD

**Issue by zanderzhng** [Outsetini/Air-for-Steam#113]
it's like
<img width="616" alt="screen shot 2016-04-15 at 4 38 33" src="https://cloud.githubusercontent.com/assets/867749/14541269/113170a8-02c4-11e6-87d4-53ed6d5d6882.png">

should be like 
<img width="361" alt="screen shot 2016-04-15 at 4 37 05" src="https://cloud.githubusercontent.com/assets/867749/14541279/1b805dd0-02c4-11e6-9688-30c11ea488d6.png">

**Comment by Lartza** [comment]
This happens on Linux too

**Comment by sebie** [comment]
Do you guys have the Roboto font installed?

**Comment by zanderzhng** [comment]
Is these enough?
![screen shot 2016-04-16 at 21 21 28](https://cloud.githubusercontent.com/assets/867749/14580911/35651fbe-0419-11e6-896a-5f8baee7e33f.png)

**Comment by Outsetini** [comment]
This should be fixed in the latest commit to master. I'll be rolling out an official update shortly, it just seemed silly for such a small fix. :)
