### ISSUE TITLE
Wrong color order

### ISSUE THREAD

**Issue by BenAlderfer** [Outsetini/Air-for-Steam#115]
If you're going for material design, the colors should be dark on the top bar and lighter on the lower bar.

**Comment by BenAlderfer** [comment]
It would also be cool if you changed the shade of blue to match steam's colors and make it feel natural.

**Comment by Outsetini** [comment]
Yeah, I had to improvise a little bit since Steam doesn't have the same status bar on the top that phones and ChromeOS do. It should be pretty simple to swap them around if you'd like to tweak that yourself though! The color variables are in this folder: \Air-for-Steam\Resource\colors
