### ISSUE TITLE
Text cutout ingame

### ISSUE THREAD

**Issue by BatyStar** [Outsetini/Air-for-Steam#117]
![20160430200920_1](https://cloud.githubusercontent.com/assets/15785828/14937721/796d452c-0f10-11e6-96f2-124ff0aeb6cc.jpg)
I am using czech language on laptop and can't view full text in ingame overlay. Can you please add a guide to steam group/FAQ on how to change position of these links or make it consider the lenght of text(i suppose that is not possible, so a guide would be probably the best solution)?

**Comment by Outsetini** [comment]
I wrote up a quick walkthrough in the wiki, check it out and let me know if you have any questions:
https://github.com/Outsetini/Air-for-Steam/wiki#how-to-fix-overlay-text-being-cut-off-in-other-languages

I'm closing the issue, but feel free to re-open if you still need help!
