### ISSUE TITLE
Can't access hidden games

### ISSUE THREAD

**Issue by CreamyCookie** [Outsetini/Air-for-Steam#119]
There currently doesn't seem to be a way to view hidden games.

The way described **[here](https://github.com/outsetini/Air-for-Steam/issues/90#issuecomment-149411402)** doesn't seem to work anymore. There's no "hidden" in the menu opened by clicking on little down-caret to the right of the Library menu item.

**Comment by Outsetini** [comment]
Hmm, I'm still seeing that option in the dropdown. Do you maybe not have any games hidden? (Sorry if that's a dumb question, but it's all I can think of).

Could you check the default client just to be sure. And possibly try re-downloading a fresh copy of Air just to be sure, but I honestly doubt that's the issue.

**Comment by CreamyCookie** [comment]
Oops, my fault. I just realized that didn't actually click on the caret. I just waited for the menu to appear. Now it works. Thanks.

**Comment by Outsetini** [comment]
No worries mate, cheers!
