### ISSUE TITLE
Steam Guard window has a weird bar from the original skin

### ISSUE THREAD

**Issue by cybersteel8** [Outsetini/Air-for-Steam#121]
![ss 2016-06-09 at 01 01 29](https://cloud.githubusercontent.com/assets/17291212/15917749/b51d495e-2e42-11e6-9cad-e8457cd7cd3b.png)

That's what my Steam Guard skin looks like when I use the Dark theme. First time user, so nothing else customized. Is that grey bar intended?

**Comment by Outsetini** [comment]
Yeah, that is definitely not intentional. I actually don't have the authenticator app, which is why I haven't seen that window before. Were you able to log in anyway, despite the visual glitch?

**Comment by Outsetini** [comment]
Fixed: https://github.com/Outsetini/Air-for-Steam/commit/3e84bd3cd0a6091d6197b365042b07fb5ff6cbac
