### ISSUE TITLE
Friends

### ISSUE THREAD

**Issue by Gavincm** [Outsetini/Air-for-Steam#122]
Is there a way to put the friends button back in the bottom right of steam like from the default skin? Really makes it easier to be able to message friends and see who's online faster than the friends tab under your username.

**Comment by frumpymoons** [comment]
Read the FAQ its in there.

**Comment by Outsetini** [comment]
https://github.com/Outsetini/Air-for-Steam/wiki#friends-list-shortcut

**Comment by silas229** [comment]
but it's not in the bottom right corner.

**Comment by Outsetini** [comment]
Sorry, to be clear: it's possible to add a friends shortcut to the top-right, but since there isn't a docked bar on the bottom, the bottom-right isn't doable with Air.
