### ISSUE TITLE
[never fixed duplicate] Menu labels missing despite having fonts correctly installed

### ISSUE THREAD

**Issue by Juesto** [Outsetini/Air-for-Steam#123]
Hello, I am having fonts issues as mentioned in #29 doesn't matter what configuration one picks it still doesn't work. I have installed the provided fonts but additionally i have the Google Roboto font pack which is sort of updated. The skin shouldn't be broken with these.
Do the shipped files have something special?
Windows 7 here

ps: i prefer chat, same user on steam

**Comment by Outsetini** [comment]
The font files in the repo are straight from Google Fonts, so there isn't anything special with them. I've seen a few issues around that are usually resolvable with a few tweaks.

First off, it could be a referencing issue, check this thread out: https://steamcommunity.com/groups/airforsteam/discussions/1/617336568076602167/

Also, I've seen issues where re-installing the fonts from scratch actually did solve problems. As in, a complete uninstall of the Roboto fonts, a computer reboot, and then reinstalling.

Closing this issue, feel free to re-open if this doesn't solve the issue!
