### ISSUE TITLE
Overlapping UI in Family Settings

### ISSUE THREAD

**Issue by dlennox24** [Outsetini/Air-for-Steam#128]
There seem to be a few blocks of text/buttons overlapping each other. I've attached a screenshot of what it looks like on my system (Win10, latest version of [Steam beta client](http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/869581079160140048)).

Using "colors/breeze.styles" and "themes/_light.styles" if that's helpful.

![ss 2016-09-10 at 11 07 53](https://cloud.githubusercontent.com/assets/11825880/18412335/e77582f0-7748-11e6-84c4-46758b98e082.png)

PS: Great skin. Love the minimalist design.

**Comment by lKobi** [comment]
Is probably due to the Steam Beta, the theme is working fine on the Stable Version.

**Comment by dlennox24** [comment]
You are correct. Just tested it on the stable version and it looks fine.

**Comment by Outsetini** [comment]
This should be fixed in the next release: f30392eb39be49fe57f5f55496670fcb5cebd909
