### ISSUE TITLE
Steam Blue dark buttons

### ISSUE THREAD

**Issue by Brottweiler** [Outsetini/Air-for-Steam#132]
- The text becomes dark and almost unreadable when hovering over the text in the menu
- Play buttons are [hard to see](https://i.imgur.com/ROHDzYT.png) because of text color

![](https://i.imgur.com/zaMhTcC.png)

**Comment by Outsetini** [comment]
It looks like you may have not copied over the +Extras as well when installing the blue theme:
https://github.com/Outsetini/Air-for-Steam/wiki#themes

Can you give that a shot and let me know if the problem persists?

**Comment by Brottweiler** [comment]
Oh yeah I missed that. Thanks, it looks great now!
