### ISSUE TITLE
Its not possible to set status when Air for Steam is applied.

### ISSUE THREAD

**Issue by TheHaso** [Outsetini/Air-for-Steam#135]
Hi,

When using Air, the option in stock friends list UI for setting status (like online, away, busy etc.) is not avalible to use.
![100](https://cloud.githubusercontent.com/assets/11940704/20891165/e7988b24-bb09-11e6-93d7-f314002aa510.JPG)
![101](https://cloud.githubusercontent.com/assets/11940704/20891166/e7b3a3aa-bb09-11e6-8571-a318a0442780.png)

**Comment by Outsetini** [comment]
Those options were moved to the menu in the main Steam window due to a bug with skins that isn't resolvable.
