### ISSUE TITLE
Skin doesn't show up in the dropdown

### ISSUE THREAD

**Issue by hotgeart** [Outsetini/Air-for-Steam#136]
Hi,

I'm totally new I hear about your skin on Reddit. I pushed your files into the right folder but when I want to select it in the dropdown I can't see it.

![http://i.imgur.com/94WrQiZ.png](http://i.imgur.com/94WrQiZ.png)

Thx

PS: I already restart Steam.

**Comment by Mantve** [comment]
You have to leave the skin in their folder, not just extract all the files. Create any folder and put all skin files. This should do the trick.

**Comment by hotgeart** [comment]
Thx I'm dumb :D
