### ISSUE TITLE
Library Search Bar and question about caps

### ISSUE THREAD

**Issue by Spidersouris** [Outsetini/Air-for-Steam#139]
Hey! Just discovered this Steam theme today and it looks great. Thanks for making this.

I just got one question and a suggestion.

First, it'd be great if you could add a Library Search box, like Metro for Steam's one. I know you can search in your library without a search box, but It's pretty unpractical imo. 

I also got a question: I'd like to make it so all header buttons (Store, Library, Community and my username) are capitalized. How can I do that?

Thanks!

EDIT: alright, just found there was a box for searching in the Library, my bad!

**Comment by Spidersouris** [comment]
Found how to capitalize the header buttons.

If someone's interested, here's how:

Go to Resources\styles and open _fonts.styles with a text editor.
Search for "CUINavButton" (should be at line 555-556)
Replace "font-style=regular" by "font-style=uppercase"

**Comment by sebie** [comment]
Hey, 

Nice job in finding the styling to capitalize the header.  I added an [entry](https://github.com/Outsetini/Air-for-Steam/wiki#header-capitalization) to the FAQ, detailing your steps.

Sorry for not getting back to you sooner, regarding the search box.

Thanks for contributing for Air! :trophy:
