### ISSUE TITLE
Notification doesn't always display the message if scaling is used

### ISSUE THREAD

**Issue by predr** [Outsetini/Air-for-Steam#140]
Hi. I'm having issue with notifications where most of the time message in notification is not shown. Image and user name display normally but the message display only occasionally. Happens on all notifications, achievements, chat etc. I have figured out it's because of scaling.

This happens on Ubuntu 16.04 and WIndows 7. On Ubuntu I have set "Display with largest controls" in Display settings which increases text and buttons, on my brothers WIndows 7 scaling is set to 125%.

Is there any way to make messages show when scaling is used?

**Comment by Outsetini** [comment]
Erm, this is a tough one. Notifications are a bit of a nightmare to skin and I don't have Linux or Win7 to test it out on.

You could try tweaking the font size/styles to see if that helps. This is the file for chat notifications: \Air-for-Steam\Friends\ChatMsgNotification.res

**Comment by predr** [comment]
Thanks for the info, I'll try that. Will reopen if I manage to make some progress.
