### ISSUE TITLE
Removing the + sign next to Library

### ISSUE THREAD

**Issue by predr** [Outsetini/Air-for-Steam#141]
I was able to remove + sign next to Library which irritated me to no end by constantly moving Community and Username when selecting Library. I don't think any functionality is removed as it is the same menu under Library. Is there any chance this could be fixed in future releases or is this behavior by design?

Resource/layout/uinavigatorpanel.layout
```
63,66c63,66
< 			render {
< 				0="fill( x0, y0, x1, y1, focus )"
< 				0="image( x0, y0 + 8, x1, y1, graphics/onfocus/caret_down_onfocus )"
< 			}
---
> 			//render {
> 			//	0="fill( x0, y0, x1, y1, focus )"
> 			//	0="image( x0, y0 + 8, x1, y1, graphics/onfocus/caret_down_onfocus )"
> 			//}
83a84
> 		// disabled set height and width to
86c87
< 			region=nav start=label_library height=30 width=15 x=0 y=7
---
> 			region=nav start=label_library height=0 width=0 x=0 y=7
```

**Comment by Outsetini** [comment]
I would love to kill that menu, I pleaded with Steam once upon a time to have them fix it, but alas. It needs to be there to access hidden games....

EDIT: OH MY GOD, THEY FIXED IT! Sorry, that was unexpected.

I will implement this right away, yeeeeeesssss!

**Comment by Awakened0** [comment]
What about custom categories? The ones you create when you right click a game, Set Category, then type something and Add Category. Those don't show up under the Library menu. Now I have no way of accessing my custom categories when in the grid view mode...

**Comment by Outsetini** [comment]
@Awakened0 I had overlooked that, good call and thanks for the reminder. I've addressed this in the latest update: http://steamcommunity.com/groups/airforsteam#announcements/detail/550963653018692216

**Comment by Awakened0** [comment]
Thanks! It's really odd Valve doesn't just have them under Library like everything else.
