### ISSUE TITLE
Switching Library View List to icon

### ISSUE THREAD

**Issue by Elijha** [Outsetini/Air-for-Steam#143]
I can't see how to do this with the skin active, switch from Icon view back to list view - or scale icon sizes. These don't seem to have menu options either so rely on the icon controls once  in Library.

**Comment by Outsetini** [comment]
Is this the option you are looking for?

![capture](https://cloud.githubusercontent.com/assets/8676168/22407645/5bbf3e04-e61f-11e6-8fec-41f49bcdeb4d.PNG)
