### ISSUE TITLE
Steam beta new notice dislocation

### ISSUE THREAD

**Issue by dsyo2008** [Outsetini/Air-for-Steam#145]
http://imgur.com/iWgjqr4
Please fix, thank you!

**Comment by Outsetini** [comment]
Could you let me know where exactly you are seeing that issue?

**Comment by dsyo2008** [comment]
setings-Friends,Can see this, thank you!

**Comment by Outsetini** [comment]
Thanks for the info, I was able to find this and get it fixed. Should be releasing once Steam rolls out the beta to everyone. 👍
