### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by pelomedusa** [Outsetini/Air-for-Steam#147]
Hello,
I'm using Air for Steam for a few month, you did a really good job there.
There is a little issue with the music player which can be very annoying for those who use it: there is no way to switch beetween the "Albums view", the "Artist view", the "Titles view" etc ... I think someone forgot to add the button ;) so i'm stuck with the default view: albums :'(
I'll try to fix it myself and push, but not sure if i will manage to since i never did any skins.

Have a nice day

EDIT: while looking at layouts, i realised the button exist but is just invisble when in overlay.
first screen is where the button should be
![screen1](https://cloud.githubusercontent.com/assets/15833842/23563424/eba9ea28-0046-11e7-9668-7bca034ddbbf.png)

2nd screen is when button is clicked
![screen2](https://cloud.githubusercontent.com/assets/15833842/23563445/ffa245d4-0046-11e7-9e05-d01c951b3752.png)

3rd screen is when it's visible in "real" steam (nopt overlay)
![screen3](https://cloud.githubusercontent.com/assets/15833842/23563450/08262f40-0047-11e7-8eeb-40bd3c178b92.png)

**Comment by Outsetini** [comment]
Good catch, this should be fixed for the next release!
