### ISSUE TITLE
A HiDPi version would be very appreciated.

### ISSUE THREAD

**Issue by that1communist** [Outsetini/Air-for-Steam#148]
On my laptop steam is practically unusable because there's no hidpi support, and i quite like this skin.

I have to use a special steam skin to make anything legible, and I was wondering if this theme could support that in the future, I understand I could edit it all, but having it centralized would make life much easier on update/newcomputer.

Thank you!

**Comment by Outsetini** [comment]
Yeah, I totally hear ya. This would be a pretty large undertaking and I don't have the time to devote to it at this point. I'd still love to get a fully functional Mac version up and running as well, but alas. Sorry :(
