### ISSUE TITLE
Menu options and other header text disappearing

### ISSUE THREAD

**Issue by MrJoelKelly** [Outsetini/Air-for-Steam#149]
After a seemingly unspecified amount of time, header text and menu button text disappears. This applies to in-steam overlay, steam window, right-click taskbar icon.

Issue is temporarily resolved by restarting Steam.

Reinstalling skin does not solve issue.

Tested on **v2017-0312**.

![2017-03-16 10_47_48-screenshots](https://cloud.githubusercontent.com/assets/17323031/23990367/201db25a-0a36-11e7-9659-cf2460a70470.png)
![2017-03-16 10_48_03-steam](https://cloud.githubusercontent.com/assets/17323031/23990368/201e5430-0a36-11e7-8ada-6683f73fdf0e.png)
![2017-03-16 10_48_15-new issue outsetini_air-for-steam](https://cloud.githubusercontent.com/assets/17323031/23990369/201e6790-0a36-11e7-8dab-c0b653beb84d.png)
![2017-03-16 10_49_26-dota 2](https://cloud.githubusercontent.com/assets/17323031/23990421/462fef94-0a36-11e7-8641-2bdd314f9f02.png)

**Comment by Outsetini** [comment]
Interesting, looks like there might be some issues with the Roboto Condensed and Roboto Medium fonts. Could you try opening this file in a text editor: \Air-for-Steam\Resource\styles\_fonts.styles and changing the definitions for Condensed and Medium under the Windows/Linux section at the top to just "Roboto" and see if that helps.

If that doesn't help, what OS are you on? It might work to uninstall the Roboto font families and restart, reinstall them and restart and then see if that resolves things. It could be something unhappy with that as well.

**Comment by Outsetini** [comment]
Closing unless followup is necessary.
