### ISSUE TITLE
Italic issue

### ISSUE THREAD

**Issue by camjac251** [Outsetini/Air-for-Steam#151]
I'm not sure if this is the intended effect but I had installed a few more Roboto fonts than what came with Air and I think it is currently trying to use those as well as the ones that came with Air.

I am seeing this issue within Air and I'm not sure if it's intended or not, I'm using the latest GitHub version with the dark theme and gunmetal style.
![image](https://cloud.githubusercontent.com/assets/6313132/24496500/07b183d6-14fe-11e7-866a-bf9aa4389d6a.png)
![image](https://cloud.githubusercontent.com/assets/6313132/24496543/262538a8-14fe-11e7-81a8-fef7fb00f26a.png)

The text in italic, is it supposed to be that way? On another computer without the extra fonts, it wont show it like that.

My Roboto fonts that I have installed are Roboto Black, Black Italic, Bold Italic, Condensed, Condensed Bold, Condensed Bold Italic, Condensed Italic, Condensed Light, Condensed Light Italic, Italic, Light, Light Italic, Medium, Medium Italic,Regular, Thin, and Thin Italic.

**Comment by Outsetini** [comment]
Yeah, that's definitely not how it's supposed to look. I would recommend uninstalling both of those font families completely and reinstalling them fresh after a restart (either from the Air fonts folder or directly from Google if you'd prefer). It might be something with older versions or something.

Let me know if you can't get it to work.

**Comment by camjac251** [comment]
That did fix it, I didn't know that I had been missing part of the font.
Was this a recent change? my friends list has friends appearing smaller text and games as well.
Before, it wasn't condensed.
![image](https://cloud.githubusercontent.com/assets/6313132/24688103/6ff31cf0-1983-11e7-8afb-c8128f07b970.png)

**Comment by Outsetini** [comment]
I know that Google made some slight changes to the Roboto font maybe a year and a half or two ago when they were first announcing Material Design. Perhaps it's that?

If it ends up bothering you, you can always try editing the font sizes manually in this file: \Air-for-Steam\Resource\styles\_fonts.styles.
