### ISSUE TITLE
Text color on Overlay

### ISSUE THREAD

**Issue by phantom-playR** [Outsetini/Air-for-Steam#157]
Hello, I noticied a little thing : tabs on the ingame overlay are not easy to read. (I have set the skin to blue version)
Maybe it would be better to have them white

Edit : or maybe it's just difficult to read on a dark background...

![gfgfgqgq](https://user-images.githubusercontent.com/4344835/28744563-ed8d4cc2-7463-11e7-9801-96db0c0f17bd.PNG)

**Comment by Outsetini** [comment]
This is unfortunately a downside of a few of the darker color themes. If you're using the dark theme, can you verify that you copied over the contents of the +Extras folder?

**Comment by phantom-playR** [comment]
No I just used the config.ini, and choosed   _include "resource/colors/steamblue.styles"_

**Comment by Brottweiler** [comment]
Same issue https://github.com/Outsetini/Air-for-Steam/issues/132? You probably forgot the +Extras folder as mentioned.

**Comment by phantom-playR** [comment]
Yes same issue, sorry and thank you
