### ISSUE TITLE
Friends button

### ISSUE THREAD

**Issue by limacezzz** [Outsetini/Air-for-Steam#158]
How can i change the "friends online" text for a button ?

**Comment by Outsetini** [comment]
You'd need to create your own friends .tga image and then make a few code changes. Most of it will be handled in \Air-for-Steam\Resource\layout\steamrootdialog.layout. The layout code controls are view_friends and online_friends. You can set the height of online_friends to 0, and then in the styles section above, find the corresponding block for `view_friends { textcolor=none }`. Simply add a render_bg command into this block (don't remove textcolor=none) that points to your tga image. The blocks below should give you some pointers.

You may need to do a bit of resizing in the layout code below depending on your image dimensions. You can save/restart Steam at any time to test out your changes. Steam skinning is a very test-heavy operation, so definitely don't be shy to do that.
