### ISSUE TITLE
Theme Not 100% Working

### ISSUE THREAD

**Issue by MudkipHero** [Outsetini/Air-for-Steam#159]
![screenshot 11](https://user-images.githubusercontent.com/30848698/29099565-2b7086d6-7c74-11e7-8bf0-ad09a288f660.png)

How Do I Fix This?

**Comment by CorruptComputer** [comment]
You gotta be more specific that that, what isn't working on that screenshot?

**Comment by MudkipHero** [comment]
The Colors Are Messed Up I Wanted it Be Like The Spotify Colors but it wont work, Sorry About That..

This Is What I want It To Look Like http://imgur.com/a/pWa4n

**Comment by CorruptComputer** [comment]
Did you follow the guide to change the theme of Air? https://github.com/Outsetini/Air-for-Steam/wiki#customization

**Comment by MudkipHero** [comment]
I Got It Working By Editing The Config, And Reinstalling Steam And Using The Links You Sent Me. Thank You For Helping

**Comment by Outsetini** [comment]
Thanks for the help @CorruptComputer! 👍
