### ISSUE TITLE
Does not show up in list of skins

### ISSUE THREAD

**Issue by awlayton** [Outsetini/Air-for-Steam#161]
I copied the folder from the zip into my skins folder and restarted steam, but I can only select the default skin.

![skin](https://user-images.githubusercontent.com/4231765/30080102-69677340-9250-11e7-84ba-10ed05f79d25.png)

I am running Ubuntu 16.04.3 if that matters.

**Comment by CorruptComputer** [comment]
Running Fedora 26 here with no issues. Possibly only limited to Ubuntu 16.04 or just a Steam bug. You may want to check here as well: https://github.com/ValveSoftware/steam-for-linux/issues

**Comment by Outsetini** [comment]
Yeah, I'm not sure in regards to Linux issues. I'll leave this issue open in case anyone has run into any similar issues.

**Comment by lKobi** [comment]
This is clearly not the issue with the Skin but Linux/Steam itself.

**Comment by awlayton** [comment]
I got it to work by installing to a different location (`~/.steam/skins/`)

**Comment by Outsetini** [comment]
Thanks for reporting back with your solution!
