### ISSUE TITLE
GUI Technology background

### ISSUE THREAD

**Issue by edwardjiawei** [Outsetini/Air-for-Steam#162]
Hi,

Mind if I asking what the technology powered by Steam, I always think Steam using Microsoft XAML for its UI. How portable is the .styles file, what UI Library are able to be skinned as the same with Steam?

Hopefully also discuss and document more background for the technology and skinning intro

Thanks!

**Comment by Outsetini** [comment]
Steam uses their own proprietary language (VGUI) that is somewhat similar to CSS when all is said and done. I don't know much beyond that, but they do have some info on their developer portal:

https://developer.valvesoftware.com/wiki/VGUI_Editing
