### ISSUE TITLE
'Write Review' text cut off

### ISSUE THREAD

**Issue by oscarwcl** [Outsetini/Air-for-Steam#163]
On the game details page, the link to write a review is cut off.

![image](https://user-images.githubusercontent.com/17673205/30952874-efb8ff26-a46c-11e7-9c44-ed4e06ce101b.png)

Running Arch Linux, occurs both with and without steam client beta.

**Comment by Outsetini** [comment]
It appears that Linux is rendering the font sizes larger than on Windows. You can adjust font sizes in this file: \Air-for-Steam\Resource\styles\_fonts.styles

For the write a review text, search for "rightcolumnlink" and "rightcolumntag" and try updating those values to be slightly smaller. Saving and restarting Steam will preview the changes.
