### ISSUE TITLE
Add hover color to games library

### ISSUE THREAD

**Issue by Keith94** [Outsetini/Air-for-Steam#165]
I'd like to have a subtle hover effect when mousing over games in my library. Preferably the text could turn from light gray to solid white (I'm using dark theme). How can I do it?

**Comment by Outsetini** [comment]
I'm not sure if that's possible or not, you'd have to do some digging around in the skin files to figure it out. Unfortunately, I'm not in a position where I have time to assist as much as I would usually, sorry. :/

But, again, feel free to poke around and see if you can find anything.
