### ISSUE TITLE
Blue theme & Steam Blue color

### ISSUE THREAD

**Issue by ChildishGiant** [Outsetini/Air-for-Steam#167]
![image](https://user-images.githubusercontent.com/13716824/33352164-835f8738-d49f-11e7-8d2e-ea49f57183f7.png)
![image](https://user-images.githubusercontent.com/13716824/33352328-43a161ce-d4a0-11e7-8274-d47b2f2bebde.png)
![image](https://user-images.githubusercontent.com/13716824/33352174-8e1c2a6e-d49f-11e7-9b1b-7cdc9e0b141d.png)

I don't think these two go together as well as the config makes me think they should. The issue is that the text hover color is way too close to the background color. A solution would be changing the hover color of `steamblue.styles` or just suggesting a different pairing (EG: `deepblue.styles`)

**Comment by Brottweiler** [comment]
Same issue? https://github.com/Outsetini/Air-for-Steam/issues/132

**Comment by ChildishGiant** [comment]
Yea, sorry 🤦‍♀️. Maybe it's worth making Steam, Dark and Light separate downloads / skins for ease. EG: 
![image](https://user-images.githubusercontent.com/13716824/33448849-02216950-d5ff-11e7-9e10-23b365889d06.png)

These could all come in one zip or be chosen upon downloading.

**Comment by Brottweiler** [comment]
I mean, while you edit the config to enable dark or blue theme, it does say this

```ini
//  !! IMPORTANT !!
//  If you have not already copied the theme contents out of the +Extras folder, please
//  read the full walkthrough here: https://github.com/Outsetini/Air-for-Steam/wiki#themes
```

I clearly didn't read this myself even, but it's there and you should read it when you are enableing those themes.

**Comment by ChildishGiant** [comment]
Yea I should have.

**Comment by Outsetini** [comment]
No worries, it happens. There are a lot of pluses and minuses to the single download vs separate downloads, and I've considered both. I do very much wish Steam gave us just a little bit more support so we could offer these sorts of options in less hacky ways, but alas.
