### ISSUE TITLE
Buttons: the cursor isn't a "pointer" when hovering

### ISSUE THREAD

**Issue by vankasteelj** [Outsetini/Air-for-Steam#168]
A few buttons don't turn the cursor to a pointer when hovering them, as they do with links. 
![steam_2018-01-02_14-16-12](https://user-images.githubusercontent.com/12599850/34486147-9a3e9972-efce-11e7-86e9-956e2ded288d.png)

**Comment by Outsetini** [comment]
This is an issue with Steam itself, sadly. There are a few situations, like your example, where I've had to take a non-button UI element and skin it to look and function like a button. The kicker is that I don't have the ability to change the cursor hover state.
