### ISSUE TITLE
Misplaced game list 'plus' icon

### ISSUE THREAD

**Issue by vankasteelj** [Outsetini/Air-for-Steam#169]
The 'plus' button (next to the cursor below) is on the game details instead of being in the list area
![steam_2018-01-02_14-16-37](https://user-images.githubusercontent.com/12599850/34486160-a9eb6616-efce-11e7-8205-e8e03fa8d5cd.png)

**Comment by vankasteelj** [comment]
I've currently disabled it with: 

```
    "CGamesPage_Details ListPanelColumnSelectButton" {
      padding-left=1
      padding-top=2
      image=graphics/none
      render { }
    }
```

**Comment by Outsetini** [comment]
I'm not 100% sure (not at home), but I'm pretty sure that the + button is actually in the scrollbar gutter area. If you view your library list so it shows a scrollbar, is the plus located at the top of that section?

**Comment by vankasteelj** [comment]
indeed

**Comment by vankasteelj** [comment]
Well, I guess if there is no way to set a condition, like "hide if scrollbar invisible", this can be closed. I'm not closing myself since you left it open, maybe for a reason beyond me :)

**Comment by Outsetini** [comment]
Nope, just wasn't closing in case I was incorrect about my assumption. ;)
