### ISSUE TITLE
I want to make a suggestion to the family lock icon and maybe the window control icons

### ISSUE THREAD

**Issue by ranomier** [Outsetini/Air-for-Steam#171]
Hello,

as to read in the title, i think the family lock is badly located. I think if a window is maximized it should be possible to go in the upper right corner of the screen to hit the close button and i mean the one pixel in the upper right corner.

Here is a **badly** designed proposal:

![steam suggestion](https://user-images.githubusercontent.com/7649949/37343069-b2f9f6ee-26c6-11e8-98fc-21de0f9c7c34.png)

The second proposal  i have, maybe make the buttons bigger, maybe not the icons themselfs. Maybe square buttons.

What do you guys think? Let me know :)

**Comment by Outsetini** [comment]
This isn't something that I have plans to change at this point, but thank you for the suggestion.
