### ISSUE TITLE
Overlapping text in interface settings (Beta Client)

### ISSUE THREAD

**Issue by Lifeismana** [Outsetini/Air-for-Steam#172]
With the latest beta update ( http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/1660013740954795957 ), Valve added a check to disable dpi scaling (for windows 10 only it seems) which created overlapping text with this check ( DPIScalingCheck ). I'm unsure if the overlapping selection at the top is related to that.
![steam_2018-03-24_17-00-26](https://user-images.githubusercontent.com/15911822/37866078-a441e540-2f85-11e8-930e-54acf81061f7.png)
I was able to partly solve this by putting 'DPIScalingCheck' in "[Air folder]\Steam\cached\SettingsSubInterface.res" but it doesn't solve everything
 `		place {
			control=AutoLaunchCheck,BigPictureModeCheck,UrlBarCheck,DWriteCheck,DPIScalingCheck,H264HWAccelCheck
			dir=down start=SkinCombo y=20
		}`
![image](https://user-images.githubusercontent.com/15911822/37866064-8e466428-2f85-11e8-8601-340e80c6933c.png)

**Comment by StaticRocket** [comment]
This same issue now exists beyond the beta client.
![image](https://user-images.githubusercontent.com/35777938/38005200-c6a734f2-320d-11e8-9a47-e31d9707fb3f.png)

**Comment by Outsetini** [comment]
84549473828a0e6bcf7ca71362ef2ae807e3eb41
