### ISSUE TITLE
Window boxes merging together with light theme.

### ISSUE THREAD

**Issue by penetal** [Outsetini/Air-for-Steam#179]
I notice that the light theme with breeze colors tend to have the window boxes kind of merge together when the colors are the same, making it somewhat hard to see the buttons in the window.
 
It is easily noticed when just moving the settings window over the library window.

If it is possible, please add the tinyest of outlines when using this combination, or an option to turn it on in the config.ini.

Thank you so much for the great theme.

PS if it is important:
OS: KDE Neon with breeze theme.

**Comment by Outsetini** [comment]
This is something that I probably won't be adding at this point. I'd prefer to not have to add outlines to all the windows - the issue lies in Steam's inconsistent usage of shadows behind new windows.
