### ISSUE TITLE
Any way to know what am I playing currently?

### ISSUE THREAD

**Issue by RabsRincon** [Outsetini/Air-for-Steam#180]
First of fall, thanks for this skin, I love everything about it.

There's only one missing feature that I sometimes miss from the default skin, which is the ability to see which game I'm currently playing directly from the friends list? Is there any other place on the UI where this is offered (Note that going to my profile page would not be a good solution), or can this be enabled in some way? I've not been able to find either.

:)

**Comment by Outsetini** [comment]
The new steam beta friends update should resolve this issue.
