### ISSUE TITLE
Invisible Menu Bar Icons

### ISSUE THREAD

**Issue by shephern** [Outsetini/Air-for-Steam#181]
Using Windows 7, running Steam Beta.

This issue appeared recently on my Air-2016/dark skin, along with square friend avatars.
I downloaded and setup Air-2018/dark, but the error persisted.  
These icons are still there, and I can interact with them properly, but they are invisible.
Changing the color theme doesn't change the issue.
Below is an image, note that not only are the menu buttons not there, but the exit, full screen, and minimize buttons aren't there as well.
This issue is also seen for my other Steam windows (e.g. Friends)

![screenshot 2018-04-27 11 51 11](https://user-images.githubusercontent.com/25040020/39379910-94c8fd64-4a11-11e8-9b96-405b5598bcc5.png)

![screenshot 2018-04-27 11 58 32](https://user-images.githubusercontent.com/25040020/39380166-78185f10-4a12-11e8-9b60-f72bfd4d1950.png)

**Comment by StaticRocket** [comment]
Launch Steam in dev mode ("<path_to_steam> -dev" in a terminal), press F6 to bring up the VGUI tool and use this to select the hidden buttons. Reply back with whatever appears in the "Layout" section to see if the skin is being applied properly.

**Comment by Outsetini** [comment]
It sounds like perhaps some of the image files were deleted or not properly extracted upon install. I would recommend starting with a fresh copy of the skin to see if that fixes the issue.
