### ISSUE TITLE
Is there support for the new text beta?

### ISSUE THREAD

**Issue by ChildishGiant** [Outsetini/Air-for-Steam#185]
There's a [new steam beta](https://steamcommunity.com/updates/chatupdate) that buffs the text and voice chat since they jealous of discord. Is support planned/in place for this?

**Comment by Brottweiler** [comment]
![image](https://user-images.githubusercontent.com/1613137/41316518-e439ac68-6e92-11e8-8e88-15d4a8485f8c.png)
Can't even get rid of that "now in beta" popup.

**Comment by NitroxydeX** [comment]
@Brottweiler you can! just scroll to the right and hit the X

**Comment by wowweemip-fan** [comment]
Please fix ASAP.

**Comment by Brottweiler** [comment]
@NitroxydeX I wasn't able to scroll to the right actually, but I realise now that there's a scrollbar at the bottom. I tried to use shift+scroll to scroll horizontally. But thanks!

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/41367338-a2666f02-6f36-11e8-889a-8b1ec4533906.png)
Yea it doesn't work well

**Comment by ChildishGiant** [comment]
I've just turned off the skin for now. It makes the hamburger menu a pain to use.

**Comment by NitroxydeX** [comment]
@Brottweiler you could use the middle mousebutton click too ^^

**Comment by Brottweiler** [comment]
@NitroxydeX Not sure if I can do that on linux, if you mean the "middle click to scroll" feature. :blush:

**Comment by f0rb1d** [comment]
I opened up a new pull request which fixs the problem, check it out.
