### ISSUE TITLE
New steam features notice window

### ISSUE THREAD

**Issue by darovic** [Outsetini/Air-for-Steam#187]
As of the latest steam client update (release https://store.steampowered.com/news/42269/) the window talking about the new features has shown up cramped in a corner and cannot be resized.

I've justed cloned the master branch in response to the update. I know it's not been updated for the public release, but hopefully this helps identify new client layouts that need to be catered for.

Or, I broke something ^^ Screenshot attached. Thank you for the awesome work.
![2018-07-25](https://user-images.githubusercontent.com/2281064/43176721-58a7e114-9008-11e8-9e9b-417404ecbc94.png)

**Comment by timritzer** [comment]
Can confirm. I also have my username scrunched up top right with a hidden menu on hover.

I have the 04-06 release FYI

**Comment by timritzer** [comment]
Taking the latest of master fixed my second issue. The feature popup remains, not sure what other things will use that window, so it may or may not matter after dismissal.

Overall still looks good. You guys rock.

**Comment by Outsetini** [comment]
Should be fixed by 9ec9749d20341ef4c2e326cf55f9f9bf46af1b42
