### ISSUE TITLE
Friends List and Wallet after new steam update

### ISSUE THREAD

**Issue by Mibo5354** [Outsetini/Air-for-Steam#188]
Friends list shortcut and the wallet is stuck up the top left corner.
![2018-07-25-164501_1366x768_scrot](https://user-images.githubusercontent.com/16360349/43183925-2a7cf49c-902a-11e8-9271-a278faca84bf.png)

**Comment by StaticRocket** [comment]
Is this a clone of the current Master branch or a version release, because it looks like a version release.

**Comment by Outsetini** [comment]
This should be fixed by the changes on the master branch and the update I'm rolling out today.
