### ISSUE TITLE
It's not working well with Windows 10 17704.

### ISSUE THREAD

**Issue by ycfung** [Outsetini/Air-for-Steam#189]
The sides are incomplete on Windows 17704
![screenshot](https://s1.ax1x.com/2018/07/25/PtNAbR.png)

**Comment by benjaminreichDE** [comment]
Its not a windows problem. Valve change a lot of the interface in the last update.

**Comment by ycfung** [comment]
Yeah the problem existed before the last update

**Comment by Outsetini** [comment]
This should be fixed by today's update, will be releasing in a few moments.
