### ISSUE TITLE
Invisible Menu

### ISSUE THREAD

**Issue by f380cedric** [Outsetini/Air-for-Steam#191]
There is an invisible menu.

![invisible_menu](https://user-images.githubusercontent.com/10184070/43282233-d5003df2-9115-11e8-8234-e7649ca95456.png)

### Additional info
Steam: not beta
Air for Steam: 2018-0725
OS: Windows

**Comment by StaticRocket** [comment]
That would be the new account menu. The new update is really doing some weird things and there's a lot that needs to be updated to keep up.

**Comment by Outsetini** [comment]
Hmm, this is because you have no wallet balance and the new UI element isn't set up to handle that gracefully. I'm working on a fix, hang tight.

**Comment by whisperity** [comment]
There isn't a graceful way to take this menu apart, right?

**Comment by StaticRocket** [comment]
The only "graceful" way to avoid an element position dependency chain is to manually place elements using x y coordinates and margins, or by setting up regions.

**Comment by Outsetini** [comment]
8ad17a928a5d6a7875562a21ef4881e84cd1de89 should fix this issue
