### ISSUE TITLE
Friend list shortcut and the wiki

### ISSUE THREAD

**Issue by f380cedric** [Outsetini/Air-for-Steam#192]
In the [Wiki](https://github.com/Outsetini/Air-for-Steam/wiki#friends-list-shortcut), it is indicated that it is possible to add a friend list shortcut. However, the method is outdated. These code blocks are no longer present.

Is there another method (update the wiki) or has this feature disappeared (delete this entry)?

**Comment by Outsetini** [comment]
This is no longer valid with the new chat ui update. I'll update the wiki - thanks for the reminder.
