### ISSUE TITLE
"Interface" Settings page has overlapping text

### ISSUE THREAD

**Issue by conkeating** [Outsetini/Air-for-Steam#193]
![screenshot from 2018-07-27 23-37-38](https://user-images.githubusercontent.com/3664453/43352764-91b3f94e-91f6-11e8-9698-dea1c928c830.png)

As shown in the attached screenshot, some of the options on the "Interface" settings page overlap. More or  less the same issue as #7 but with a different section of text.

**Comment by Outsetini** [comment]
Two quick questions and I can get this fixed up. 
1: Are you on OSX or Linux?
2: Can you disable Air and take a screenshot of the interface settings page with the default skin enabled?

**Comment by conkeating** [comment]
Linux, and here you go!
![screenshot from 2018-07-28 00-12-25](https://user-images.githubusercontent.com/3664453/43352981-fbf3c952-91fa-11e8-90aa-355079b8b7f9.png)

**Comment by Outsetini** [comment]
That should do it! Let me know if it's still misbehaving after that latest commit.
