### ISSUE TITLE
Friends Window and Profile Button are broken with latest Steam UI Update

### ISSUE THREAD

**Issue by Rcarballo2222** [Outsetini/Air-for-Steam#195]

**Comment by biggles5107** [comment]
By "broken," I'm assuming you mean not themed. Everything renders correctly; just the new UI keeps the default look (which is obviously not what we want).

**Comment by Outsetini** [comment]
See this post: https://steamcommunity.com/groups/metroforsteam#announcements/detail/1645384648842466293

TLDR: The new UI is not skinnable.

**Comment by biggles5107** [comment]
Well that's unfortunate. I quite liked this theme.

**Comment by Outsetini** [comment]
Yeah, I wish it was under our control... Steam has never been very supportive of skinning, so I'm not surprised to see them doing away with it with these new updates.
