### ISSUE TITLE
Download icon not showing

### ISSUE THREAD

**Issue by julien404** [Outsetini/Air-for-Steam#197]
Hello, i've a problem with the download icon: it doesn't show it but i can click on it, even when there is no downloads active.
Any idea? 
I've the latest release (28/07/2018).

**Comment by AlexVincent525** [comment]
Found too. This is UIStatusPanel, and it always display as StatusComplete / URLLabel.
![image](https://user-images.githubusercontent.com/15884415/43599141-40beff9e-96b9-11e8-9bf5-a3495a430f10.png)
Air's author may not have spare time to figure out this, I'll try later see where the error is.

**Comment by iceJourney** [comment]
have noticed too, from the last version (0725) and this new one (0728).
an invisible download button is on the bottom right corner where I pinned in the attached pic.
![snipaste_2018-08-03_19-23-38](https://user-images.githubusercontent.com/18734597/43640852-15e870ac-9754-11e8-8ec2-eeda1748a1d0.jpg)

**Comment by Outsetini** [comment]
Ugh, it looks like Valve decided to change the zpos value of the downloads section of the skin so it always renders behind the main content. The icon is there, but this implementation may no longer be possible...

**Comment by Outsetini** [comment]
Fixed with some compromises in ef099cd
