### ISSUE TITLE
Can't drag windows intuitively when there is a search box

### ISSUE THREAD

**Issue by budomino** [Outsetini/Air-for-Steam#199]
So, it seems this skin's implementation of Material has difficulty working with mice due to the usually drag-able title/function bar containing a search box in some windows.

My biggest issue seems to be trying to move my many popup windows for visibility, but the Library section also seems to be a problem in the main window.

I think the quickest workaround would be to keep the textbox underline visible even when the textbox is not selected, but a long term solution would be to use one of the other search box implementations within material's guidelines: https://material.io/design/components/text-fields.html

**Comment by Outsetini** [comment]
This isn't something I have plans to change at this point.
