### ISSUE TITLE
Mac missing icon issue

### ISSUE THREAD

**Issue by MikeStardust** [outsetini/Air-for-Steam#60]
so i have installed your theme and everything is running smoothly except for the main menu icon on the main window, its just not there:
![screen shot 2015-07-04 at 21 46 59](https://cloud.githubusercontent.com/assets/5862135/8509360/709e3760-2296-11e5-9b9c-c574c135a91a.png)

running OS X 10.10.3 (14D136)

Great skin, thanks

**Comment by sebie** [comment]
Thanks for submitting an issue. I just have a few questions.

* Does this occur in new release?
* Is it a clean install?
* Have you installed the Roboto fonts?

**Comment by MikeStardust** [comment]
Thanks for the help,
* Yeah newest release downloaded yesterday from your site
* As clean as it gets, just re-installed steam
* Yeah i had them all before cause of a web project, still i replaced them with your version

**Comment by Elundris** [comment]
Ah, that is because the menus on Mac are located on the OSX UI instead of Steam. Because of this, the main menu button is hidden.

I haven't had a chance to fully compatibilize (that is so not a word) Air with OSX yet, thus why there is still an empty space. This is one of my goals moving forward though!

**Comment by MikeStardust** [comment]
Fair enough mate! Thanks! 
You should leave the button there anyways, even with no action looks kinda better !
Cheers

**Comment by gxgani** [comment]
The missing icon still seems to bother me

**Comment by Seranok** [comment]
Guess you could give this round to windows.

**Comment by outsetini** [comment]
Archiving this for now. If I get more time to tackle an OSX version, this will definitely be on the list.
