### ISSUE TITLE
Friends List Tweak

### ISSUE THREAD

**Issue by NuclearMeltdown** [outsetini/Air-for-Steam#79]
I know, this isn't really an issue, but for me, it's kind of an inconvenience. The problem I have is that I cannot see myself in my friends list like in the standard Steam skin or in almost every other skin... That causes me to sometimes forget that I'm still in-game when I'm looking at my friends list, I have to always go to my profile... Also I cannot set my status to away, offline, etc from my friends list and have to go to the top-left corner of the main Steam screen and do that. The feature could also be implemented into the main Steam screen but the friends list would be just fine. It also doesn't have to be implemented as standard but an optional tweak would be pretty nice. I mean the option existed in the Air Classic skin but seems to have been removed in the new one (or at least I haven't seen it in the customization part of the readme, if I did overlook it, please tell me where to look). I hope you'll consider adding that feature as optional tweak, thank you! 

![image](https://cloud.githubusercontent.com/assets/6499567/9914328/a50c676a-5cb1-11e5-9d26-edf905eb2383.png)

Update: 
Information about people you're currently talking to would be nice too, as you can only see if said person is online, offline or in-game (but you don't know in which game, you always have to look at the friends list), which is another little inconvenience for me, while the information could easily be placed in the huge space in the window over the names:

![image](https://cloud.githubusercontent.com/assets/6499567/9916670/d7312148-5cbd-11e5-9306-a8bbcdd50065.png)

But otherwise, Air is my favorite Steam skin so far and it would be perfect if these two options would be added.

**Comment by Elundris** [comment]
This has been something on the backburner for awhile now, I just haven't found a way to implement it that I am satisfied with. I won't make any promises, but I'll keep this ticket open as a reminder.

As for the chat window, you should be able to hover over their avatar to see which game they are playing. Due to the way Valve coded the chat window, I'm unable to use the top space in any useful capacity (other than removing it, which would be bad for consistency throughout the skin). :/

**Comment by Seranok** [comment]
I would recommend the user's name be highlighted in Green color if he is online and red if offline.

**Comment by smiley** [comment]
I'd also love to have this back. And maybe statuses could be added to the little context menu in the Friends dialog?

**Comment by outsetini** [comment]
Archiving.
