### ISSUE TITLE
Lag when Writing in a Group Chat

### ISSUE THREAD

**Issue by kazritsu** [outsetini/Air-for-Steam#93]
Hello
Whenever I write with my friends in a Group Chat, there is a noticeable lag when using this Skin.
I have tried others and they don't have this problem, but they don't look as good as Air ;)
Thanks

**Comment by Elundris** [comment]
I will look into this on my next bugfix pass, thanks for the report!

**Comment by z96** [comment]
I noticed the same issue, googled it, and came across this page.
I don't recall when I downloaded the skin, but it was quite a bit after Oct 22nd.

**Comment by outsetini** [comment]
Sorry for the delay on getting this fixed guys - this should fix the lag, odd little bug! I'll have it out with the next release, but feel free to grab the develop branch in the meantime if you'd like.

If it doesn't appear fixed for either of you, please re-open.

**Comment by z96** [comment]
Appears to have worked for me! Great work :)
