### ISSUE TITLE
Adjust Close/Maximize/Minimize Icons?

### ISSUE THREAD

**Issue by JamesCoyle** [outsetini/Air-for-Steam#96]
Is there any chance these icons could be made easier to click on? The click target is way too small. I'd suggest they be resized to be the full height of the bar and 45px wide.

**Comment by outsetini** [comment]
This would cause issues with some of the smaller dialog boxes (check for client updates, for example), where I actually don't have any control over the placement of the icons. Thus why they looks so cramped on some of these dialogs as well. :/
