### ISSUE TITLE
Overlapping UI elements in SteamGuard notification window

### ISSUE THREAD

**Issue by aclonegeek** [outsetini/Air-for-Steam#98]
After letting someone else log into my account (to set up Steam Family Sharing), I logged back in and was prompted with this window. When I highlighted either the NO or YES buttons, their highlight indicator overlapped into the opposite button's area. 

Also, the Learn more button is unaligned with the NO and YES buttons.

I was using [Hotfix: 2015-1012a](https://github.com/outsetini/Air-for-Steam/tree/2015-1012a). The only changes I've made to the skin are text colours and nothing more.

**Normal**
![2015-10-15_17-32-03](https://cloud.githubusercontent.com/assets/9111965/12211008/1c06b18a-b62c-11e5-9e04-de93b0e3440a.png)
**NO highlighted**
![2015-10-15_17-32-09](https://cloud.githubusercontent.com/assets/9111965/12211007/1c05f042-b62c-11e5-815e-f858fae83d75.png)
**YES highlighted**
![2015-10-15_17-32-14](https://cloud.githubusercontent.com/assets/9111965/12211009/1c07705c-b62c-11e5-8a4d-2943eab151f7.png)

**Comment by outsetini** [comment]
Huh, I have literally never seen that window and I've definitely done some family sharing around on other computers... I thought Valve was doing all their Steam Guard stuff in the mobile app, email, or web client these days. Did you do anything special when setting up Steam Guard? I have mine sending messages via email, are you using the mobile app?

It wouldn't be too hard of a fix, but I'd need to get it to appear on my end or there's not too much I can do.

**Comment by aclonegeek** [comment]
I don't believe I've done anything special setting up SteamGuard. The screenshots were taken on October 15th, which was before all the mobile authentication came around (I believe). Regardless, I've always had SteamGuard set to email. Perhaps this dialogue will appear if you deauthorize all computers (or specifically the one you can test with) and try setting up the sharing again.

I'm sure you've done the same thing as I have (or similar for any matter) but just in case, these are the steps I took for setting up family sharing (and getting this message):
1. Logged out of my steam account
2. Logged into my steam account on the other computer
3. Prompted with SteamGuard code insertion window - went to my email and typed it in
4. After logging into my account on the other computer, I went into Settings > Family > Authorize this computer and hit OK
5. Logged out
6. Logged back into my account on my main PC and was prompted with the message

**Comment by outsetini** [comment]
That may indeed have been before they started solidifying the Steam Guard stuff into the mobile/web interface.

I'll keep my eye out for the issue moving forward, and if you end up running into it again, let me know. I'm crossing my fingers that they removed this dialog from the client in favor of the web interface though. We'll see. :)

**Comment by aclonegeek** [comment]
Will do! Thanks for looking into it.

**Comment by outsetini** [comment]
Closing ticket for now, please don't hesitate to re-open it if you see the issue again.
