### ISSUE TITLE
Broadcast popout bug

### ISSUE THREAD

**Issue by sgtsarge** [outsetini/Air-for-Steam#99]
While watching a Steam broadcast and using the popout feature, the window will only render when it is on top of the main Steam window.  If the popout window does not overlap at all with the main Steam window it will become completely white or grey depending on theme. Version 2015-1012a.

Using a public broadcast as an example:
![airbug1](https://cloud.githubusercontent.com/assets/14044925/12223412/1a3a1c2a-b794-11e5-8a04-117a40e7e436.png)
![airbug2](https://cloud.githubusercontent.com/assets/14044925/12223413/1a3a6446-b794-11e5-9e59-624c62b04e3e.png)

**Comment by outsetini** [comment]
Thanks for the report, found the culprit and nailed it down. This will be included in the next update, and if you need to use pop-out in the meantime, feel free to grab a copy of the develop branch for now.
